#!/usr/bin/env deno --allow-read --allow-write --allow-env

// See `docs/adding_timing_metadata.md` for an explanation of listing times, and
// a walkthrough on adding entries for new tests.

// See the help message in this file for info on how to use the tool.
import '../src/common/tools/merge_listing_times.ts';
